version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

# Erstellt HTML und ePub (da du beides willst!)
formats:
  - htmlzip
  - epub

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc  

# Deine Sphinx-Konfiguration
sphinx:
  configuration: doc/source/conf.py
  builder: dirhtml
